# Generated by Django 5.2.17 on 2026-10-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_perfiles_desde_grupos(apps, schema_editor):
    PerfilUsuario = apps.get_model("inventario", "PerfilUsuario")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    database = schema_editor.connection.alias
    grupos_roles = {
        "Administrador": "admin",
        "Almacenista": "almacenista",
        "Cajero": "cajero",
    }

    for usuario in (
        User.objects.using(database)
        .prefetch_related("groups")
        .iterator(chunk_size=200)
    ):
        roles = {
            grupos_roles[grupo.name]
            for grupo in usuario.groups.all()
            if grupo.name in grupos_roles
        }
        if len(roles) == 1:
            PerfilUsuario.objects.using(database).create(
                usuario_id=usuario.pk,
                rol=roles.pop(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('almacenista', 'Almacenista'), ('cajero', 'Cajero')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(crear_perfiles_desde_grupos, migrations.RunPython.noop),
    ]
