# Generated by Django 5.2.17 on 2026-10-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='talla',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
